language: swift
osx_image: xcode8
script:
 - xcodebuild -version
 - xcodebuild -workspace SortonsEvents.xcworkspace -scheme SortonsEventsTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
 - bash <(curl -s https://codecov.io/bash) -cF ios
branches:
 only:
 - dev
