# 1
price_tier 0
# 2
app_review_information(
  first_name: "Brian",
  last_name: "Henry",
  phone_number: "+353 404 70100",
  email_address: "brian.henry@sortons.ie",
  demo_user: "N/A",
  demo_password: "N/A",
  notes: "No demo account needed"
)
# 3
submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})
# 4
automatic_release true
# 5
app_icon './fastlane/metadata/app_icon.png'
# 6
app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"
