//
//  ListEventsModels.swift
//  SortonsEvents
//
//  Created by Brian Henry on 04/07/2016.
//  Copyright (c) 2016 Sortons. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListEvents_FetchEvents_Request {
}

struct ListEvents_FetchEvents_Response {
    let events : [DiscoveredEvent]
}

struct ListEventsViewModel {
    let discoveredEvents : [DiscoveredEventCellModel]
}

struct DiscoveredEventCellModel {
    let webUrl: NSURL
    let appUrl : NSURL
    let name: String
    let startTime : String
    let location: String?
    let imageUrl : NSURL
}

